version: "3.8"
services:
  web:
    build: ./ecomv2
    ports:
      - "3000:3000"
    volumes:
      - ./ecomv2:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: 800m
  nodejs:
    build: ./back
    environment:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=mystrongpassword
      - MYSQL_DATABASE=ecomv2
      - MYSQL_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./back:/app
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: 512m
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecomv2
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: mystrongpassword
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512m
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    networks:
      - app-network
    mem_limit: 512m
networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:
    driver: local
